image: "${GITLAB_DOCKER_PROXY}/eclipse-temurin:25-jdk-alpine"

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  GITLAB_DOCKER_PROXY: "gitlab.education.tbank.ru:443/backend-academy-java-2025/lecture-materials/dependency_proxy/containers"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_PROTECTED == 'true'
    - if: $CI_COMMIT_BRANCH == 'master'

stages:
  - build
  - lint
  - test
  - migration

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository/

build:
  stage: build
  script:
    - ./mvnw package -DskipTests=true -Djacoco.skip=true

lint:
  stage: lint
  needs:
    - build
  script:
    - ./mvnw compile -am spotless:check modernizer:modernizer spotbugs:check pmd:check pmd:cpd-check

test:
  stage: test
  needs:
    - build
  services:
    - name: docker:29.0.1-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "${DOCKER_TLS_CERTDIR}/client"
    TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX: "${GITLAB_DOCKER_PROXY}/"
  tags:
    - dind
  before_script:
    - apk add --no-cache docker-cli
    - echo "DOCKER_HOST=$DOCKER_HOST"
    - echo "DOCKER_TLS_CERTDIR=$DOCKER_TLS_CERTDIR"
    - echo "DOCKER_TLS_VERIFY=$DOCKER_TLS_VERIFY"
    - echo "DOCKER_CERT_PATH=$DOCKER_CERT_PATH"
    - ls -la /certs || true
    - ls -la /certs/client || true
    - docker version || true
    - docker info || true
    - echo "$CI_JOB_TOKEN" | docker login gitlab.education.tbank.ru:443 -u gitlab-ci-token --password-stdin
  script:
    - ./mvnw package -DskipTests=true -Djacoco.skip=true
    - docker build -t linktracker-bot:latest ./bot
    - docker build -t linktracker-scrapper:latest ./scrapper
    - docker images
    - ./mvnw verify

migration:
  stage: migration
  services:
    - name: postgres:16
      alias: postgres
  variables:
    POSTGRES_DB: postgres_db
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
  script:
    - |
      ./mvnw \
        -pl scrapper liquibase:update \
        -Dliquibase.url=jdbc:postgresql://postgres:5432/$POSTGRES_DB \
        -Dliquibase.username=$POSTGRES_USER \
        -Dliquibase.password=$POSTGRES_PASSWORD \
        -Dliquibase.changeLogFile=scrapper/src/main/resources/db/changelog/db.changelog-master.yaml
