version: '3.9'

services:
  kafka-1:
    image: apache/kafka:3.9.1
    hostname: kafka
    container_name: kafka-1
    ports:
      - "19092:19092"
    environment:
      - KAFKA_NODE_ID=0
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka-1:9093

      - KAFKA_LISTENERS=BROKER://kafka-1:9092,CONTROLLER://kafka-1:9093,DOCKER://0.0.0.0:19092
      - KAFKA_ADVERTISED_LISTENERS=BROKER://kafka-1:9092,DOCKER://localhost:19092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,DOCKER:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=BROKER
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
