server:
  port: 8081

spring:
  application:
    name: scrapper

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none

  ##data:
   ## redis:
    ##  host: ${SPRING_DATA_REDIS_HOST:localhost}
   ##   port: ${SPRING_DATA_REDIS_PORT:6379}


  kafka:
    bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
    producer:
      properties:
        acks: 1
        batch.size: 1024
        linger.ms: 10000
        spring.json.add.type.headers: false

resilience4j.retry:
  instances:
    githubRetry:
      maxAttempts: 3
      waitDuration: 500
      exponential-backoff-multiplier: 2
      enable-exponential-backoff: true
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - org.springframework.web.client.ResourceAccessException
      ignoreExceptions:
        - org.springframework.web.client.HttpClientErrorException

resilience4j.circuitbreaker:
  instances:
    stackOverFlowBreaker:
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 20
      slidingWindowSize: 20
      failureRateThreshold: 50
      waitDurationInOpenState: 5s
      permittedNumberOfCallsInHalfOpenState: 2


resilience4j.ratelimiter:
  instances:
    getLinks:
      limitForPeriod: 5
      timeout-duration: 0s
      limitRefreshPeriod: 5s



app:
  scheduler:
    page: 0
    size: 50
    check: 10000
    threads: 4
  repository-type: jdbc
  message-transport: http #kafka
  stackoverflow:
    url: ${APP_STACKOVERFLOW_URL:https://api.stackexchange.com}
    key: ${STACKOVERFLOW_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
    url-path-endpoint: /2.3/questions/{id}
    url-path-answer: /2.3/questions/{id}/answers
    url-path-comment: /2.3/questions/{id}/comments

  github:
    url: ${APP_GITHUB_URL:https://api.github.com}
    token: ${GITHUB_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    url-endpoint: /repos/{owner}/{repo}/issues
  bot:
    url: ${APP_BOT_URL:http://localhost:8080}
    update-endpoint: /updates

  message-send:
    topic: link.raw-updates
    #dlq-topic: message-send-dlq
    partitions: 3
    replicas: 3

  ##valkey:
    ##channel: ${APP_VALKEY_CHANNEL:links:invalidate}


