CREATE TABLE IF NOT EXISTS tags(
    id BIGSERIAL PRIMARY KEY,
    tag TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS link_tag(
    tag_id BIGINT REFERENCES tags(id) ON DELETE CASCADE,
    link_id BIGINT REFERENCES links(id) ON DELETE CASCADE,
    PRIMARY KEY(link_id, tag_id)
);
