server:
  port: 8080

spring:
  application:
    name: bot
config:
  import:
    optional:
      file: .env
app:
  telegram:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    update-listener-sleep: 1s
    debug: false
  scrapper:
    url: http://localhost:8081
  messages:
    first: "Добро пожаловать! Используйте /help, чтобы посмотреть доступные команды."
    start: "Бот уже работает"
    help: |
      На данный момент доступны команды
      /start - начало работы
      /help - список команд

    unknown: |
      Неизвестная команда.
      Воспользуйтесь /help





