server:
  port: 8080

spring:
  application:
    name: bot
  kafka:
    bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: consumer-2
      properties:
        enable.auto.commit: false
        auto.offset.reset: latest
        isolation.level: read_committed
        fetch.min.bytes: 1024
        fetch.max.bytes: 1048576
        fetch.max.wait.ms: 10000
        max.poll.interval.ms: 10000
        max.poll.records: 10

config:
  import:
    optional:
      file: .env

app:
  telegram:
    url: ${APP_TELEGRAM_URL:https://api.telegram.org/bot}
    token: ${TELEGRAM_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    update-listener-sleep: 1s
    debug: false
  scrapper:
    url: ${APP_SCRAPPER_URL:http://localhost:8081}
    chat-endpoint: /tg-chat/{id}
    link-endpoint: /links
    header: Tg-Chat-Id
  message-transport: http #kafka
  messages:
    first: "Добро пожаловать! Используйте /help, чтобы посмотреть доступные команды."
    start: "Бот уже работает."
    help: |
      На данный момент доступны команды
      /start - начало работы
      /help - список команд
      /list <tag> - список отслеживаемых ссылок с тегом
      /track - добавить ссылку для отслеживания
      /untrack - перестать отслеживать ссылку
    list: "Нет отслеживаемых ссылок."
    cancel: "Действие отменено."
    track-link: "Пришлите ссылку для отслеживания."
    track-tags: "Теперь пришлите теги через запятую. Отправьте -, если теги не нужны."
    invalid-link: "Ссылка некорректна."
    track-success: "Ссылка добавлена в отслеживание."
    link-already-exists: "Ссылка уже отслеживается"

    untrack-link: "Пришлите ссылку для удаления."
    untrack-success: "Ссылка больше не отслеживается."

    link-not: "Ссылка не найдена"

    unknown: |
      Неизвестная команда.
      Воспользуйтесь /help

  kafka:
    topic: message-send
    dlq-topic: message-send-dlq
    retry-attempts: 3
    retry-backoff-ms: 1000
    fail-on-processing: false



