server:
  port: 8080

spring:
  application:
    name: bot
config:
  import:
    optional:
      file: .env
app:
  telegram:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    update-listener-sleep: 1s
    debug: false
  scrapper:
    url: http://localhost:8081
  messages:
    first: "Добро пожаловать! Используйте /help, чтобы посмотреть доступные команды."
    start: "Бот уже работает."
    help: |
      На данный момент доступны команды
      /start - начало работы
      /help - список команд
    list: "Нет отслеживаемых ссылок."
    cancel: "Действие отменено."
    track-link: "Пришлите ссылку для отслеживания."
    track-tags: "Теперь пришлите теги через запятую. Если теги не нужны — отправьте пустое сообщение."
    invalid-link: "Ссылка некорректна."
    track-success: "Ссылка добавлена в отслеживание."
    link-already-exists: "Ссылка уже отслеживается"

    untrack-link: "Пришлите ссылку для удаления."
    untrack-success: "Ссылка больше не отслеживается."

    link-not: "Ссылка не найдена"

    unknown: |
      Неизвестная команда.
      Воспользуйтесь /help





